# Glicko-2 leaderboard (series-based)

This notebook displays a compact leaderboard from `data/metrics/glicko2_latest_all.parquet`.

Notes:
- Ratings are computed on **series outcomes** (keyed by `(leagueid, series_id)`), not per-map.
- If you changed `glicko2_config.json`, rerun `make precompute GLICKO_CONFIG=glicko2_config.json` before opening this notebook.

In [1]:
from pathlib import Path
import sys

import polars as pl
import pandas as pd


def find_root() -> Path:
    cand = Path.cwd()
    for c in [cand, *cand.parents]:
        if (c / "src").exists() and (c / "data").exists():
            return c
    return cand


ROOT = find_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

PROCESSED_DIR = ROOT / "data" / "processed"
METRICS_DIR = ROOT / "data" / "metrics"

G2_LATEST_ALL_PATH = METRICS_DIR / "glicko2_latest_all.parquet"
SERIES_RESULTS_PATH = METRICS_DIR / "series_results.parquet"

ALIASES_PATH = ROOT / "data" / "team_aliases.csv"

print("ROOT:", ROOT)
print("PROCESSED_DIR:", PROCESSED_DIR)
print("METRICS_DIR:", METRICS_DIR)
print("glicko2_latest_all.parquet exists?", G2_LATEST_ALL_PATH.exists())
print("series_results.parquet exists?", SERIES_RESULTS_PATH.exists())

ROOT: /home/ju/Documents/Dev/MachineLearning/Dota-Datas
PROCESSED_DIR: /home/ju/Documents/Dev/MachineLearning/Dota-Datas/data/processed
METRICS_DIR: /home/ju/Documents/Dev/MachineLearning/Dota-Datas/data/metrics
glicko2_latest_all.parquet exists? True
series_results.parquet exists? True

In [2]:
def must_read_parquet(path: Path) -> pl.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run: make precompute OUT=data/processed METRICS_OUT=data/metrics (and set GLICKO_CONFIG if needed)."
        )
    return pl.read_parquet(path)


g2_latest_all = must_read_parquet(G2_LATEST_ALL_PATH)
series_results = must_read_parquet(SERIES_RESULTS_PATH)

g2_latest_all.head(3), series_results.head(3)

(shape: (3, 7)
 ┌─────────┬─────────────┬───────────┬──────────┬─────────────┬──────┬────────────┐
 │ team_id ┆ rating      ┆ rd        ┆ sigma    ┆ score       ┆ rank ┆ score_rank │
 │ ---     ┆ ---         ┆ ---       ┆ ---      ┆ ---         ┆ ---  ┆ ---        │
 │ i64     ┆ f64         ┆ f64       ┆ f64      ┆ f64         ┆ u32  ┆ u32        │
 ╞═════════╪═════════════╪═══════════╪══════════╪═════════════╪══════╪════════════╡
 │ 7119388 ┆ 2164.97338  ┆ 90.807029 ┆ 0.060036 ┆ 1983.359322 ┆ 1    ┆ 1          │
 │ 9247354 ┆ 2144.449284 ┆ 90.860557 ┆ 0.059998 ┆ 1962.728169 ┆ 2    ┆ 2          │
 │ 9823272 ┆ 2058.482785 ┆ 89.540571 ┆ 0.06007  ┆ 1879.401642 ┆ 3    ┆ 3          │
 └─────────┴─────────────┴───────────┴──────────┴─────────────┴──────┴────────────┘,
 shape: (3, 13)
 ┌──────────┬───────────┬────────────┬──────────────┬───┬──────┬─────────┬─────────────┬────────┐
 │ leagueid ┆ series_id ┆ start_time ┆ start_dt     ┆ … ┆ maps ┆ bo_type ┆ series_type ┆ weight │
 │ ---      ┆ ---       ┆ ---        ┆ ---          ┆   ┆ ---  ┆ ---     ┆ ---         ┆ ---    │
 │ i64      ┆ i64       ┆ i64        ┆ datetime[μs, ┆   ┆ i64  ┆ i64     ┆ i64         ┆ f64    │
 │          ┆           ┆            ┆ UTC]         ┆   ┆      ┆         ┆             ┆        │
 ╞══════════╪═══════════╪════════════╪══════════════╪═══╪══════╪═════════╪═════════════╪════════╡
 │ 16093    ┆ 838795    ┆ 1704355281 ┆ 2024-01-04   ┆ … ┆ 1    ┆ 1       ┆ 1           ┆ 1.05   │
 │          ┆           ┆            ┆ 08:01:21 UTC ┆   ┆      ┆         ┆             ┆        │
 │ 16093    ┆ 838802    ┆ 1704358792 ┆ 2024-01-04   ┆ … ┆ 1    ┆ 1       ┆ 1           ┆ 1.05   │
 │          ┆           ┆            ┆ 08:59:52 UTC ┆   ┆      ┆         ┆             ┆        │
 │ 16093    ┆ 838796    ┆ 1704358994 ┆ 2024-01-04   ┆ … ┆ 2    ┆ 3       ┆ 3           ┆ 1.05   │
 │          ┆           ┆            ┆ 09:03:14 UTC ┆   ┆      ┆         ┆             ┆        │
 └──────────┴───────────┴────────────┴──────────────┴───┴──────┴─────────┴─────────────┴────────┘)

In [3]:
from src.dota_data import read_processed_tables, build_team_dictionary

tables = read_processed_tables(PROCESSED_DIR)
teams_dict = build_team_dictionary(tables["matches"])

teams = (
    teams_dict.group_by("team_id")
    .agg(
        pl.col("name").drop_nulls().first().alias("team_name"),
        pl.col("tag").drop_nulls().first().alias("tag"),
        pl.col("logo_url").drop_nulls().first().alias("logo_url"),
    )
    .filter(pl.col("team_id").is_not_null())
)

teams.head(5)

shape: (5, 4)
┌─────────┬──────────────┬───────┬─────────────────────────────────┐
│ team_id ┆ team_name    ┆ tag   ┆ logo_url                        │
│ ---     ┆ ---          ┆ ---   ┆ ---                             │
│ i64     ┆ str          ┆ str   ┆ str                             │
╞═════════╪══════════════╪═══════╪═════════════════════════════════╡
│ 9651867 ┆ saadboys     ┆ saD   ┆ https://cdn.steamusercontent.c… │
│ 9917833 ┆ Atlantis 2.0 ┆       ┆ https://cdn.steamusercontent.c… │
│ 9382454 ┆ COPPYBEBRA   ┆ COPPY ┆ https://cdn.steamusercontent.c… │
│ 8815475 ┆ Ghost Trick  ┆ GTR   ┆ https://cdn.steamusercontent.c… │
│ 9337731 ┆ LEVIATAN     ┆ LEV   ┆ https://cdn.steamusercontent.c… │
└─────────┴──────────────┴───────┴─────────────────────────────────┘

In [4]:
# Per-team series volume and last seen date (helps interpret RD / uncertainty)
a = series_results.select(
    pl.col("team_a_id").cast(pl.Int64, strict=False).alias("team_id"),
    pl.col("start_time").cast(pl.Int64, strict=False).alias("start_time"),
).with_columns(pl.lit(1).alias("series"))
b = series_results.select(
    pl.col("team_b_id").cast(pl.Int64, strict=False).alias("team_id"),
    pl.col("start_time").cast(pl.Int64, strict=False).alias("start_time"),
).with_columns(pl.lit(1).alias("series"))

series_stats = (
    pl.concat([a, b], how="vertical")
    .drop_nulls(["team_id"])
    .group_by("team_id")
    .agg(
        pl.sum("series").alias("series_played"),
        pl.max("start_time").alias("last_start_time"),
    )
)

series_stats.head(5)

shape: (5, 3)
┌──────────┬───────────────┬─────────────────┐
│ team_id  ┆ series_played ┆ last_start_time │
│ ---      ┆ ---           ┆ ---             │
│ i64      ┆ i32           ┆ i64             │
╞══════════╪═══════════════╪═════════════════╡
│ 9162769  ┆ 1             ┆ 1705312676      │
│ 10026852 ┆ 1             ┆ 1768230676      │
│ 9723788  ┆ 3             ┆ 1746870789      │
│ 9895247  ┆ 123           ┆ 1769002341      │
│ 9571336  ┆ 1             ┆ 1731507254      │
└──────────┴───────────────┴─────────────────┘

In [5]:
# Leaderboards
df = (
    g2_latest_all
    .join(teams, on="team_id", how="left")
    .join(series_stats, on="team_id", how="left")
)

df_pd = df.to_pandas()
if "last_start_time" in df_pd.columns:
    df_pd["last_series_dt"] = pd.to_datetime(df_pd["last_start_time"], unit="s", utc=True)

cols = [
    "score_rank",
    "rank",
    "team_id",
    "team_name",
    "rating",
    "rd",
    "score",
    "series_played",
    "last_series_dt",
]
cols = [c for c in cols if c in df_pd.columns]

TOP_N = 30

display(df_pd.sort_values("score_rank", ascending=True)[cols].head(TOP_N))

print("\nTop by raw rating (rank):")
display(df_pd.sort_values("rank", ascending=True)[cols].head(TOP_N))

,score_rank,rank,team_id,team_name,rating,rd,score,series_played,last_series_dt
0,1,1,7119388,Team Spirit,2164.973380,90.807029,1983.359322,276,2025-12-21 18:17:01+00:00
1,2,2,9247354,Team Falcons,2144.449284,90.860557,1962.728169,296,2026-01-18 20:31:21+00:00
2,3,3,9823272,Team Yandex,2058.482785,89.540571,1879.401642,72,2025-12-21 18:17:01+00:00
3,4,4,8255888,BetBoom Team,2043.587245,86.997358,1869.592530,272,2026-01-17 19:03:05+00:00
6,5,7,9338413,MOUZ,2033.207658,83.069567,1867.068524,295,2026-01-20 13:21:30+00:00
4,6,5,9572001,PVISION,2040.654800,88.538748,1863.577304,165,2026-01-05 17:22:46+00:00
5,7,6,8291895,Tundra Esports,2038.127162,90.683779,1856.759604,299,2025-12-19 19:00:00+00:00
9,8,10,8261500,Xtreme Gaming,1981.252747,89.859706,1801.533336,255,2026-01-05 14:59:36+00:00
10,9,11,36,Natus Vincere,1952.421274,78.948927,1794.523421,177,2026-01-20 17:47:13+00:00
11,10,12,2586976,OG,1934.660011,91.042383,1752.575245,244,2025-12-20 13:15:00+00:00
12,11,13,2163,Team Liquid,1930.508966,89.157277,1752.194413,289,2026-01-20 13:21:30+00:00
21,12,22,9467224,Aurora Gaming,1868.700979,82.648059,1703.404861,193,2026-01-18 15:00:11+00:00
18,13,19,9640842,Team Tidebound,1892.314143,95.429525,1701.455093,123,2025-12-15 13:31:03+00:00
23,14,24,9303484,HEROIC,1859.587295,88.470154,1682.646987,254,2026-01-20 23:25:49+00:00
8,15,9,9766941,FLIPSTER TALON,1984.650458,152.346431,1679.957596,23,2025-10-01 11:55:29+00:00
24,16,25,9729720,Virtus.pro,1853.255657,89.329374,1674.596910,171,2026-01-24 15:03:53+00:00
15,17,16,9885654,Team Aureus,1915.759911,126.720188,1662.319535,30,2025-10-19 15:30:03+00:00
28,18,29,8254145,Execration,1818.035914,87.084103,1643.867707,193,2026-01-18 11:22:01+00:00
16,19,17,9824702,PARIVISION,1914.181206,143.890749,1626.399708,19,2025-10-27 12:08:50+00:00
25,20,26,9964962,GamerLegion,1840.992114,107.483864,1626.024385,19,2026-01-19 01:55:25+00:00
13,21,14,8599101,Gaimin Gladiators,1923.949492,149.873008,1624.203476,210,2025-08-21 18:58:07+00:00
35,22,36,7554697,Nigma Galaxy,1792.128547,93.678910,1604.770727,197,2026-01-22 17:25:06+00:00
43,23,44,9255039,Klim Sani4,1766.813037,83.164011,1600.485015,252,2026-01-23 13:45:06+00:00
42,24,43,9828897,REKONIX,1769.477429,86.290496,1596.896438,75,2026-01-18 11:22:01+00:00
49,25,50,9758040,Runa Team,1754.870935,93.689222,1567.492490,141,2025-12-15 12:09:01+00:00
59,26,60,9895247,Rune Eaters,1722.060757,81.977145,1558.106466,123,2026-01-21 13:32:21+00:00
57,27,58,9872667,Pipsqueak+4,1723.828325,83.122536,1557.583252,67,2026-01-23 10:03:01+00:00
73,28,74,9600141,Zero Tenacity,1693.406586,81.141979,1531.122628,236,2026-01-24 11:37:15+00:00
64,29,65,9928746,Most Wanted,1709.474632,89.302328,1530.869976,63,2025-12-28 18:06:20+00:00
14,30,15,9538207,Myth Avenue Gaming,1916.213137,195.168223,1525.876691,25,2026-01-11 13:54:12+00:00

Top by raw rating (rank):

,score_rank,rank,team_id,team_name,rating,rd,score,series_played,last_series_dt
0,1,1,7119388,Team Spirit,2164.973380,90.807029,1983.359322,276,2025-12-21 18:17:01+00:00
1,2,2,9247354,Team Falcons,2144.449284,90.860557,1962.728169,296,2026-01-18 20:31:21+00:00
2,3,3,9823272,Team Yandex,2058.482785,89.540571,1879.401642,72,2025-12-21 18:17:01+00:00
3,4,4,8255888,BetBoom Team,2043.587245,86.997358,1869.592530,272,2026-01-17 19:03:05+00:00
4,6,5,9572001,PVISION,2040.654800,88.538748,1863.577304,165,2026-01-05 17:22:46+00:00
5,7,6,8291895,Tundra Esports,2038.127162,90.683779,1856.759604,299,2025-12-19 19:00:00+00:00
6,5,7,9338413,MOUZ,2033.207658,83.069567,1867.068524,295,2026-01-20 13:21:30+00:00
7,53,8,9547255,Bandanoone,1985.389265,282.284146,1420.820973,4,2024-09-29 18:32:32+00:00
8,15,9,9766941,FLIPSTER TALON,1984.650458,152.346431,1679.957596,23,2025-10-01 11:55:29+00:00
9,8,10,8261500,Xtreme Gaming,1981.252747,89.859706,1801.533336,255,2026-01-05 14:59:36+00:00
10,9,11,36,Natus Vincere,1952.421274,78.948927,1794.523421,177,2026-01-20 17:47:13+00:00
11,10,12,2586976,OG,1934.660011,91.042383,1752.575245,244,2025-12-20 13:15:00+00:00
12,11,13,2163,Team Liquid,1930.508966,89.157277,1752.194413,289,2026-01-20 13:21:30+00:00
13,21,14,8599101,Gaimin Gladiators,1923.949492,149.873008,1624.203476,210,2025-08-21 18:58:07+00:00
14,30,15,9538207,Myth Avenue Gaming,1916.213137,195.168223,1525.876691,25,2026-01-11 13:54:12+00:00
15,17,16,9885654,Team Aureus,1915.759911,126.720188,1662.319535,30,2025-10-19 15:30:03+00:00
16,19,17,9824702,PARIVISION,1914.181206,143.890749,1626.399708,19,2025-10-27 12:08:50+00:00
17,38,18,9634742,Chimera Esports,1895.887416,199.456773,1496.973870,38,2025-03-01 16:40:07+00:00
18,13,19,9640842,Team Tidebound,1892.314143,95.429525,1701.455093,123,2025-12-15 13:31:03+00:00
19,35,20,9798195,Cyber Goose,1884.722174,188.424629,1507.872916,12,2025-06-13 15:19:12+00:00
20,58,21,9594647,PuckChamp,1878.684534,246.939514,1384.805507,7,2024-11-17 16:20:11+00:00
21,12,22,9467224,Aurora Gaming,1868.700979,82.648059,1703.404861,193,2026-01-18 15:00:11+00:00
22,33,23,1725846,Chimpanzini Bananini,1866.421150,176.691299,1513.038552,9,2025-09-27 02:12:14+00:00
23,14,24,9303484,HEROIC,1859.587295,88.470154,1682.646987,254,2026-01-20 23:25:49+00:00
24,16,25,9729720,Virtus.pro,1853.255657,89.329374,1674.596910,171,2026-01-24 15:03:53+00:00
25,20,26,9964962,GamerLegion,1840.992114,107.483864,1626.024385,19,2026-01-19 01:55:25+00:00
26,67,27,8605863,Cloud9,1834.812618,243.306010,1348.200599,56,2024-09-14 09:20:37+00:00
27,64,28,9895699,tearlaments,1830.623323,234.112719,1362.397886,3,2025-10-05 10:58:06+00:00
28,18,29,8254145,Execration,1818.035914,87.084103,1643.867707,193,2026-01-18 11:22:01+00:00
29,70,30,9593895,Gaozu,1810.067046,236.069055,1337.928936,9,2024-12-11 09:34:10+00:00