# Elo overview

Exploration rapide des Elo (global et par patch) générés dans `data/metrics/`.
Plots allégés pour rester lisibles (top restreint, rang hebdo) et table leaderboard.

In [1]:
from pathlib import Path
import polars as pl
import pandas as pd
import plotly.express as px

def find_root() -> Path:
    cand = Path.cwd()
    for c in [cand, *cand.parents]:
        if (c / "data" / "metrics").exists():
            return c
    return cand

ROOT = find_root()
METRICS_DIR = ROOT / "data" / "metrics"
TS_PATH = METRICS_DIR / "elo_timeseries.parquet"
LATEST_PATH = METRICS_DIR / "elo_latest.parquet"
PATCH_LATEST_PATH = METRICS_DIR / "elo_patch_latest.parquet"
TRACKED_PATH = METRICS_DIR / "tracked_teams.parquet"

def load_df(path: Path) -> pl.DataFrame | None:
    if path.exists():
        return pl.read_parquet(path)
    print(f"Missing: {path}")
    return None

elo_ts = load_df(TS_PATH)
elo_latest = load_df(LATEST_PATH)
elo_patch_latest = load_df(PATCH_LATEST_PATH)
tracked = load_df(TRACKED_PATH)

names_map = {}
if tracked is not None and not tracked.is_empty():
    for r in tracked.iter_rows(named=True):
        tid = r.get("team_id") or r.get("TeamID")
        nm = r.get("name") or r.get("TeamName")
        if tid is not None and nm:
            names_map[int(tid)] = nm

def add_names(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty or not names_map:
        return df
    df = df.copy()
    df["team_name"] = df["team_id"].map(names_map)
    df["team_label"] = df.apply(
        lambda r: f"{r['team_name']} ({r['team_id']})" if pd.notnull(r.get('team_name')) else r['team_id'], axis=1
    )
    return df

elo_ts_pandas = add_names(elo_ts.to_pandas()) if elo_ts is not None and not elo_ts.is_empty() else pd.DataFrame()
elo_latest_pandas = add_names(elo_latest.to_pandas()) if elo_latest is not None and not elo_latest.is_empty() else pd.DataFrame()
elo_patch_latest_pandas = add_names(elo_patch_latest.to_pandas()) if elo_patch_latest is not None and not elo_patch_latest.is_empty() else pd.DataFrame()
elo_ts_pandas.head()

,match_id,start_time,start_dt,team_id,opponent_id,team_is_radiant,team_win,rating_pre,rating_post,rating_pre_patch,rating_post_patch,expected,expected_patch,tournament_tier,tournament_location,weight,patch,team_name,team_label
0,7520706781,1704355281,2024-01-04 08:01:21,8588969,9081007,False,0,1500.000000,1480.207524,1500.000000,1480.207524,0.471249,0.471249,qualifier,online,1.05,54,HYDRA,HYDRA (8588969)
1,7520706865,1704355380,2024-01-04 08:03:00,2576071,9279613,False,1,1500.000000,1522.207524,1500.000000,1522.207524,0.471249,0.471249,qualifier,online,1.05,54,Yellow Submarine,Yellow Submarine (2576071)
2,7520754303,1704358792,2024-01-04 08:59:52,8588969,9081007,False,0,1480.207524,1462.774110,1480.207524,1462.774110,0.415081,0.415081,qualifier,online,1.05,54,HYDRA,HYDRA (8588969)
3,7520761790,1704358994,2024-01-04 09:03:14,2576071,9279613,True,1,1522.207524,1539.358100,1522.207524,1539.358100,0.591653,0.591653,qualifier,online,1.05,54,Yellow Submarine,Yellow Submarine (2576071)
4,7523989094,1704528110,2024-01-06 08:01:50,8376696,9216247,True,1,1500.000000,1519.792476,1500.000000,1519.792476,0.528751,0.528751,qualifier,online,1.05,54,One Move,One Move (8376696)

## Top 20 actuel (global)
Affiche les 20 meilleurs Elo globaux (avec labels si disponibles).

In [3]:
if elo_latest_pandas.empty:
    print("No elo_latest available")
else:
    top20 = elo_latest_pandas.sort_values("elo", ascending=False).head(10)
    y_col = "team_label" if "team_label" in top20.columns else "team_id"
    fig = px.bar(top20, x="elo", y=y_col, orientation="h", title="Top 10 Elo (global)", text="elo")
    fig.update_layout(yaxis=dict(autorange="reversed"))
    fig.update_traces(texttemplate="%{text:.1f}", textposition="outside")
    fig.show()
    display(top20[["team_id", "team_name", "elo"]])

   team_id        team_name          elo
0  9247354     Team Falcons  1955.748845
1  7119388      Team Spirit  1915.597809
2  9572001          PVISION  1900.978797
3  8291895   Tundra Esports  1890.674325
4  9338413             MOUZ  1861.609263
5     2163      Team Liquid  1827.933511
6  9823272      Team Yandex  1820.878223
7  8255888          BB Team  1818.308657
8  9766941   FLIPSTER TALON  1783.003350
9  9634742  Chimera Esports  1778.915298

In [2]:
if elo_latest_pandas.empty:
    print("No elo_latest available")
else:
    top20 = elo_latest_pandas.sort_values("elo", ascending=False).head(20)
    y_col = "team_label" if "team_label" in top20.columns else "team_id"
    fig = px.bar(top20, x="elo", y=y_col, orientation="h", title="Top 20 Elo (global)", text="elo")
    fig.update_layout(yaxis=dict(autorange="reversed"))
    fig.update_traces(texttemplate="%{text:.1f}", textposition="outside")
    fig.show()
    display(top20[["team_id", "team_name", "elo"]])

    team_id          team_name          elo
0   9247354       Team Falcons  1955.748845
1   7119388        Team Spirit  1915.597809
2   9572001            PVISION  1900.978797
3   8291895     Tundra Esports  1890.674325
4   9338413               MOUZ  1861.609263
5      2163        Team Liquid  1827.933511
6   9823272        Team Yandex  1820.878223
7   8255888            BB Team  1818.308657
8   9766941     FLIPSTER TALON  1783.003350
9   9634742    Chimera Esports  1778.915298
10  8261500      Xtreme Gaming  1770.348302
11       36      Natus Vincere  1767.061060
12  9255039            1w Team  1763.073252
13  8599101  Gaimin Gladiators  1762.341520
14  9467224      Aurora Gaming  1755.573779
15  9828897            REKONIX  1753.464621
16  9640842     Team Tidebound  1739.847792
17  9303484             HEROIC  1729.800589
18  9798195        Cyber Goose  1729.420877
19  9928746        Most Wanted  1713.006692

## Évolution du top 10 (rank hebdo)

Dernier Elo par équipe et par semaine; rang hebdo; on trace les équipes qui sont au moins une fois dans le top 10.

In [4]:
if elo_ts_pandas.empty:
    print("No elo_timeseries available")
else:
    ts = elo_ts_pandas.copy()
    ts["start_dt"] = pd.to_datetime(ts["start_time"], unit="s")
    ts["week"] = ts["start_dt"].dt.to_period("W").apply(lambda r: r.start_time)
    ts_weekly = ts.sort_values(["team_id", "start_dt"]).groupby(["team_id", "week"]).tail(1)
    ts_weekly["rank"] = ts_weekly.groupby("week")["rating_post"].rank(ascending=False, method="dense")
    ts_top = ts_weekly[ts_weekly["rank"] <= 10]
    y_col = "team_label" if "team_label" in ts_top.columns else "team_id"
    fig = px.line(
        ts_top,
        x="week",
        y="rank",
        color=y_col,
        hover_data=["rating_post"],
        title="Évolution du top 10 Elo (global, hebdo)",
    )
    fig.update_yaxes(autorange="reversed")
    fig.show()
    display(ts_top[["week", "team_id", "team_name", "rank", "rating_post"]].head())

           week  team_id      team_name  rank  rating_post
1697 2024-03-18       36  Natus Vincere  10.0  1595.646200
3119 2024-05-20       36  Natus Vincere  10.0  1558.304600
4882 2024-07-29       36  Natus Vincere  10.0  1600.319432
5181 2024-08-12       36  Natus Vincere   9.0  1595.780883
6475 2024-10-07       36  Natus Vincere   5.0  1647.343930

## Top Elo par patch (top 10 par patch)

In [5]:
if elo_patch_latest_pandas.empty:
    print("No elo_patch_latest available")
else:
    top_patch = (
        elo_patch_latest_pandas.sort_values(["patch", "elo"], ascending=[True, False])
        .groupby("patch")
        .head(10)
    )
    y_col = "team_label" if "team_label" in top_patch.columns else "team_id"
    fig = px.bar(
        top_patch,
        x="elo",
        y=y_col,
        color="patch",
        orientation="h",
        title="Top 10 Elo par patch",
    )
    fig.update_layout(yaxis=dict(autorange="reversed"))
    fig.show()
    display(top_patch[["patch", "team_id", "team_name", "elo"]])

     patch  team_id          team_name          elo
0       54  9247354       Team Falcons  1832.503880
1       54  8261500      Xtreme Gaming  1793.329358
2       54  7119388        Team Spirit  1728.558514
3       54  8291895     Tundra Esports  1710.130644
4       54  8599101  Gaimin Gladiators  1695.502974
5       54  2586976                 OG  1668.830376
6       54  9017006        NAVI Junior  1647.018705
7       54  8255888            BB Team  1646.176158
8       54  9338413               MOUZ  1644.095411
9       54     2163        Team Liquid  1633.236693
41      55  8599101  Gaimin Gladiators  1875.777475
42      55  2586976                 OG  1790.711034
43      55  9255039            1w Team  1782.857035
44      55  9247354       Team Falcons  1765.986488
45      55  8291895     Tundra Esports  1732.740928
46      55     2163        Team Liquid  1731.443311
47      55  7119388        Team Spirit  1689.074188
48      55  8255888            BB Team  1686.101310
49      55  8261500      Xtreme Gaming  1660.955800
50      55  7732977       BOOM Esports  1641.013399
81      56  8291895     Tundra Esports  1958.286704
82      56  8255888            BB Team  1879.568996
83      56  7119388        Team Spirit  1873.209260
84      56  9247354       Team Falcons  1868.404748
85      56  9572001            PVISION  1852.982174
86      56  9640842     Team Tidebound  1799.524408
87      56     2163        Team Liquid  1792.153737
88      56  8597976              Talon  1782.389356
89      56  7554697       Nigma Galaxy  1775.313349
90      56  9303484             HEROIC  1761.095432
171     57  9572001            PVISION  1954.009650
172     57  7119388        Team Spirit  1897.795308
173     57  8291895     Tundra Esports  1893.280063
174     57     2163        Team Liquid  1859.625785
175     57  9467224      Aurora Gaming  1821.503290
176     57  9640842     Team Tidebound  1796.851083
177     57  8599101  Gaimin Gladiators  1779.578750
178     57  8255888            BB Team  1764.488840
179     57  7554697       Nigma Galaxy  1753.297365
180     57  9247354       Team Falcons  1741.610431
251     58  9247354       Team Falcons  1951.121458
252     58  7119388        Team Spirit  1895.518949
253     58  9572001            PVISION  1877.369819
254     58  8291895     Tundra Esports  1868.256742
255     58  9338413               MOUZ  1845.106907
256     58     2163        Team Liquid  1807.190288
257     58  9823272        Team Yandex  1805.621964
258     58  8255888            BB Team  1793.971592
259     58  9766941     FLIPSTER TALON  1772.538794
260     58  8261500      Xtreme Gaming  1769.293358

## Leaderboard complet (global)

In [6]:
if elo_latest_pandas.empty:
    print("No elo_latest available")
else:
    leaderboard = elo_latest_pandas.copy()
    leaderboard["elo_rank"] = leaderboard["elo"].rank(ascending=False, method="dense").astype(int)
    leaderboard = leaderboard.sort_values("elo_rank").reset_index(drop=True)
    cols = [c for c in ["elo_rank", "team_id", "team_name", "elo"] if c in leaderboard.columns]
    display(leaderboard[cols].head(50))

    elo_rank  team_id          team_name          elo
0          1  9247354       Team Falcons  1955.748845
1          2  7119388        Team Spirit  1915.597809
2          3  9572001            PVISION  1900.978797
3          4  8291895     Tundra Esports  1890.674325
4          5  9338413               MOUZ  1861.609263
5          6     2163        Team Liquid  1827.933511
6          7  9823272        Team Yandex  1820.878223
7          8  8255888            BB Team  1818.308657
8          9  9766941     FLIPSTER TALON  1783.003350
9         10  9634742    Chimera Esports  1778.915298
10        11  8261500      Xtreme Gaming  1770.348302
11        12       36      Natus Vincere  1767.061060
12        13  9255039            1w Team  1763.073252
13        14  8599101  Gaimin Gladiators  1762.341520
14        15  9467224      Aurora Gaming  1755.573779
15        16  9828897            REKONIX  1753.464621
16        17  9640842     Team Tidebound  1739.847792
17        18  9303484             HEROIC  1729.800589
18        19  9798195        Cyber Goose  1729.420877
19        20  9928746        Most Wanted  1713.006692
20        21  9381678       Apex Genesis  1708.598467
21        22  9699158        tearlaments  1708.444201
22        23  9824702         PARIVISION  1708.190894
23        24  9885654        Team Aureus  1699.807211
24        25  2586976                 OG  1696.380958
25        26  9814008           eSpoiled  1691.107021
26        27  9373270        Night Pulse  1682.986738
27        28  9303383          L1GA TEAM  1668.769978
28        29  8597976              Talon  1666.226388
29        30  9885130       Perú Rejects  1665.210515
30        31  9351740    Yakult Brothers  1663.942112
31        32  9872667        Pipsqueak+4  1663.486063
32        33  9885667           Team Tea  1662.653250
33        34  7554697       Nigma Galaxy  1650.723076
34        35  9758040          Runa Team  1647.688862
35        36       39  Shopify Rebellion  1647.681040
36        37  7732977       BOOM Esports  1646.018634
37        38  8254145         Execration  1632.527578
38        39  9729720         Virtus.pro  1627.269425
39        40  9664724        ITB.Shuffle  1618.721418
40        41  9956508        Team Public  1618.175322
41        42  9247798         Passion UA  1615.581959
42        43  9716354   Tech Free Gaming  1614.344024
43        44  1838315        Team Secret  1613.144583
44        45  9450071     Fusion Esports  1611.155175
45        46  9646485            Jigglin  1610.166188
46        47  9790546    TEAM NEXT LEVEL  1610.091947
47        48  9593627              Titan  1607.344134
48        49  8574561          Azure Ray  1601.588628
49        50  9498970             AVULUS  1600.466320